apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
  labels:
    label1: test
# spec:
#   minReplicas: 1
#   maxReplicas: 3
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: redis
#   metrics:
#   - external:
#       metric:
#         name: System.cpu.user
#       target:
#         type: AverageValue
#         averageValue: 50
#     type: External

spec:
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redis
  metrics:
  - type: External
    external:
      metric:
        name: system.cpu.user
        selector:
          matchLabels:
            kube_cluster_name: test-cluster
      target:
        type: Value
        value: 2
  behavior:
    scaleDown:
      policies:
      - type: Pods
        value: 4
        periodSeconds: 60
