apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    clusterName: opCluster
    credentials:
      apiSecret:
        secretName: datadog-agent
        keyName: api-key
    kubelet:
      tlsVerify: false
  override:
    nodeAgent:
      containers:
        trace-agent:
          env:
            - name: DD_APM_IGNORE_RESOURCES
              valueFrom:
                configMapKeyRef:
                  name: datadog-trace-agent-env-vars
                  key: DD_APM_IGNORE_RESOURCES
        agent:
          env:
            - name: "DD_IGNORE_AUTOCONF"
              value: "kube_controller_manager kube_scheduler etcd"
      # Add overrides to the Cluster Agent
    clusterAgent:
      replicas: 1
