# apiVersion: datadoghq.com/v2alpha1
# kind: DatadogAgent
# metadata:
#   name: datadog
# spec:
#   global:
#     site: datadoghq.eu
#     credentials:
#       apiSecret:
#         secretName: datadog-secret
#         keyName: api-key
#   features:
#     logCollection:
#       enabled: true
#       containerCollectAll: true
#     npm:
#       enabled: true
kind: DatadogAgent
apiVersion: datadoghq.com/v2alpha1
metadata:
  name: datadog
spec:
  features:
    logCollection:
      enabled: false
    liveProcessCollection:
      enabled: false
    liveContainerCollection:
      enabled: true
    apm:
      enabled: false
    cspm:
      enabled: false
    cws:
      enabled: false
    npm:
      enabled: false
    admissionController:
      enabled: false
    externalMetricsServer:
      enabled: false
      useDatadogMetrics: false
  global:
    credentials:
      apiSecret:
        secretName: datadog-agent
        keyName: api-key
    clusterName: rancher-cluster
    kubelet:
      tlsVerify: false
  override:
    clusterAgent:
      image:
        name: gcr.io/datadoghq/cluster-agent:latest
    nodeAgent:
      image:
        name: gcr.io/datadoghq/agent:latest
      tolerations:
        - key: node-role.kubernetes.io/controlplane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/etcd
          operator: Exists
          effect: NoExecute
