version: '3'
services:
  datadog:
    image: gcr.io/datadoghq/agent:7
    container_name: datadog
    pid: host
    environment:
     - DD_API_KEY=<MY_API_KEY>
     - DD_SITE=datadoghq.com
     - DD_LOGS_ENABLED=true
     - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
     - DD_CONTAINER_EXCLUDE=name:datadog
     - DD_LOG_LEVEL=info
     - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /var/lib/docker/containers:/var/lib/docker/containers:ro
     - /proc/:/host/proc/:ro
     - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    ports:
      - "8125:8125/udp"
  python-dsd:
    image: python-dsd:udp
    container_name: dsd
    environment:
     - DD_AGENT_HOST=datadog
