apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
spec:
  containers:
  - name: busybox-container
    image: busybox
    command: ["sh", "-c", "echo 'Pod is running...'; sleep 3600"]
    resources:
      requests:
        cpu: 100m
      limits:
        cpu: 100m
