datadog:
  apiKeyExistingSecret: datadog-secret
  clusterName: your-gke-cluster
  kubelet:
    tlsVerify: false 
  logs:
    enabled: true
    containerCollectAll: true
  processAgent:
    enabled: true
    processCollection: true