# Example data to return for our example openmetrics server
kind: ConfigMap
apiVersion: v1
metadata:
  name: openmetrics-data
  namespace: default
data:
  example-data: |-    
  
    # HELP http_server_duration
    # TYPE http_server_duration gauge
    http_server_duration{name="hello",tag_extra="a"} 5.0
    http_server_duration{name="hello",tag_extra="b"} 10.0
    http_server_duration{name="world",tag_extra="a"} 15.0
    http_server_duration{name="world",tag_extra="b"} 20.0
    http_server_duration{name="world",tag_extra="c"} 25.0

    # HELP http_server_requests
    # TYPE http_server_requests counter
    http_server_requests{name="hello",tag_extra="a"} 1.0
    http_server_requests{name="hello",tag_extra="b"} 2.0
    http_server_requests{name="world",tag_extra="a"} 3.0
    http_server_requests{name="world",tag_extra="b"} 4.0
    http_server_requests{name="world",tag_extra="c"} 5.0

    # HELP http_server_histogram_duration
    # TYPE http_server_histogram_duration histogram
    http_server_histogram_duration_bucket{name="hello",le="0.25"} 3.0
    http_server_histogram_duration_bucket{name="hello",le="0.50"} 10.0
    http_server_histogram_duration_bucket{name="hello",le="0.75"} 5.0
    http_server_histogram_duration_bucket{name="hello",le="0.99"} 2.0
    http_server_histogram_duration_bucket{name="hello",le="+Inf"} 1.0
    http_server_histogram_duration_count{name="hello"} 1
    http_server_histogram_duration_sum{name="hello"} 21
    http_server_histogram_duration_max{name="hello"} 88

    # HELP metric_a
    # TYPE metric_a counter
    metric_a{database="db1"} 5.0
    metric_a{database="db2"} 10.0

    # HELP metric_b
    # TYPE metric_b counter
    metric_b{type="type1",database="db1"} 5.0
    metric_b{type="type2",database="db2"} 10.0

    # HELP database_queries
    # TYPE database_queries counter
    database_queries{name="hello",database="db1"} 5.0
    database_queries{name="hello",database="db2"} 10.0
    database_queries{name="hello",database="db3"} 20.0
    database_queries{name="hello",database="db4"} 25.0

    # HELP http_server_requests_seconds
    # TYPE http_server_requests_seconds summary
    http_server_requests_seconds_count{exception="None",method="GET",outcome="SUCCESS",status="200",uberctx_service_name="depot",uri="/api/v1/documents/batch"} 2.0
    http_server_requests_seconds_sum{exception="None",method="GET",outcome="SUCCESS",status="200",uberctx_service_name="depot",uri="/api/v1/documents/batch"} 0.165964327

    # HELP http_server_requests_seconds_max
    # TYPE http_server_requests_seconds_max gauge
    http_server_requests_seconds_max{exception="None",method="GET",outcome="SUCCESS",status="200",uberctx_service_name="depot",uri="/api/v1/documents/batch"} 0.0
