apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: default
spec:
  selector:
    app: example-metrics
  ports:
  - name: mainport
    protocol: TCP
    port: 80
    targetPort: 8000
