targetSystem: "linux"
datadog:
  apiKeyExistingSecret: datadog-agent
  clusterName: minikube

  # Enabling Journald log collection
  # This tails the /run/log/journal/ file mounted on the agent
  confd: 
    journald.yaml: |-
      logs:
        - type: journald
          path: /run/log/journal/
  # Disabling Kubelet verification for minikube
  kubelet:
    tlsVerify: false

  kubeStateMetricsEnabled: false
  kubeStateMetricsCore:
    enabled: true
    
  logs:
    enabled: true
    containerCollectAll: false

  # Ignoring some problematic integrations on minikube
  ignoreAutoConfig:
    - etcd
    - kube_controller_manager 
    - kube_scheduler 

clusterAgent:
  enabled: true 

# Mounts the volume for journald logs onto the agent. 
# This configuration uses /run/log/journal which is the path journald logs to in Minikube
agents:
  volumes:
    - name: journald
      hostPath:
        path: /run/log/journal
  volumeMounts:
    - mountPath: /run/log/journal
      name: journald