apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    targetSystem: windows
    clusterName: opCluster
    credentials:
      apiSecret:
        secretName: datadog-agent
        keyName: api-key
    kubelet:
      tlsVerify: false
    podLabelsAsTags:
      type: type
  # features:
  # override:
  #   # Add overrides to the Cluster Agent
  #   clusterAgent:
  #     replicas: 1
  #   nodeAgent:
  #     env:
  #       - name: DD_APM_RECEIVER_SOCKET
  #         value: "/var/run/datadog/apm/apm.socket"
