targetSystem: "linux"
datadog:
  apiKeyExistingSecret: datadog-agent
  logLevel: DEBUG
  # Disabling Kubelet verification for minikube
  kubelet:
    tlsVerify: false
  # Ignoring some problematic integrations on minikube
  ignoreAutoConfig:
    - etcd
    - kube_controller_manager 
    - kube_scheduler 
  kubeStateMetricsEnabled: false
agents:
  image: 
    name: fb-agent  # image_name
    tag: v1  # image_tag
    repository: docker.io/stzou/fb-agent  # registry/repository/image_name
    doNotCheckTag: true  # set to true to bypass helm chart's version requirements