apiVersion: v1
kind: Pod
metadata:
  name: redis
  annotations:
    ad.datadoghq.com/redis.check_names: '["redisdb"]'
    ad.datadoghq.com/redis.init_configs: '[{}]'
    # Reading from a file
    # ad.datadoghq.com/redis.instances: |
    #   [
    #     {
    #       "host": "%%host%%",
    #       "port":"6379",
    #       "password":"ENC[file@/etc/secret-volume/redis_password]"
    #     }
    #   ]      

    # Reading from existing secret:
    # ad.datadoghq.com/redis.instances: |
    #   [
    #     {
    #       "host": "%%host%%",
    #       "port":"6379",
    #       "password":"ENC[k8s_secret@default/redis-secret/redis_password]"
    #     }
    #   ]      
  labels:
    name: redis
spec:
  containers:
    - name: redis
      image: redis:latest
      ports:
        - containerPort: 6379