apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: default
type: Opaque
data:
  redis_password: testing # base64 encoded text

# secret.yaml
# apiVersion: v1
# kind: Secret
# metadata:
#   name: pat-secret
# type: Opaque
# data:
#   pat-api: ZGI4ODhlODNlZjNiNzA4YjlhZGNmYTI4ZTk5ZDA2NWQ= # base64 encoded text
