targetSystem: "linux"
datadog:
  apiKeyExistingSecret: datadog-agent
  clusterName: mini

  secretBackend:
    command: "/readsecret_multiple_providers.sh"
      #Reading from Volume
      arguments: /etc/secret-volume

  # Disabling Kubelet verification for minikube
  kubelet:
    tlsVerify: false

  kubeStateMetricsEnabled: false
  kubeStateMetricsCore:
    enabled: true

  orchestratorExplorer:
    enabled: true
  logs:
    enabled: true
    containerCollectAll: false

  apm:
    socketEnabled: false
    portEnabled: false
  processAgent:
    enabled: true
    processCollection: false

  clusterChecks:
    enabled: true

  # Ignoring some problematic integrations on minikube
  ignoreAutoConfig:
    - etcd
    - kube_controller_manager 
    - kube_scheduler 

clusterAgent:
  enabled: true 

agents:
  volumes:
    - name: secret-volume
      secret:
        secretName: redis-secret
  volumeMounts:
  - name: secret-volume
    mountPath: /etc/secret-volume