##
## Attempting to use secrets for dual shipping orchestrator data on the cluster agent
## Cluster agent was not decrypting the secret properly. What's the right syntax?
##
datadog:
  clusterame: minikube
  apiKeyExistingSecret: datadog-agent
  # secretBackend:
  #   command: "/readsecret_multiple_providers.sh"
  env:
   - name: DD_SECRET_BACKEND_COMMAND
     value: /readsecret_multiple_providers.sh
  #  - name: DD_SECRET_BACKEND_ARGUMENTS
  #    value: /etc/secret-volume
agents:
  useConfigMap: true
  customAgentConfig:
    process_config:
      additional_endpoints:
        "https://process.datadoghq.com":
        - ENC[file@/etc/secret-volume/pat-api]
    orchestrator_explorer:
      orchestrator_additional_endpoints:
        "https://orchestrator.datadoghq.com":
        - ENC[file@/etc/secret-volume/pat-api]
  volumes:
   - name: pat-secret
     secret:
       secretName: pat-secret
  volumeMounts:
  - mountPath: /etc/secret-volume
    name: pat-secret
    readOnly: true

clusterAgent:
  # env:
  #   - name: DD_ORCHESTRATOR_EXPLORER_ORCHESTRATOR_ADDITIONAL_ENDPOINTS
  #     value: '{ "https://orchestrator.datadoghq.com": [ "ENC[pat-api]" ] }'
  volumes:
   - name: pat-secret
     secret:
       secretName: pat-secret
  volumeMounts:
  - mountPath: /etc/secret-volume
    name: pat-secret
    readOnly: true
  datadog_cluster_yaml:
    orchestrator_explorer:
      orchestrator_additional_endpoints:
        "https://orchestrator.datadoghq.com":
        - "ENC[file@/etc/secret-volume/pat-api]"
